package demo1package.data;

public class Address {
 //the below are private due to encapsulation
    private int houseNo;
    private String streetName;
    private String city;
    private String country;
    private int zipCode;

  //parameterized constructor is below and can be generated by right-clicking the screen and selecting constructor
    public Address(int houseNo, String streetName, String city, String country, int zipCode) {
        this.houseNo = houseNo;
        this.streetName = streetName;
        this.city = city;
        this.country = country;
        this.zipCode = zipCode;
    }
//below is the non-parameterized constructor
    public Address() {

}
//below is getter setter method
    public int getHouseNo() {
        return houseNo;
    }

    public void setHouseNo(int houseNo) {
        this.houseNo = houseNo;
    }

    public String getStreetName() {
        return streetName;
    }

    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public int getZipCode() {
        return zipCode;
    }

    public void setZipCode(int zipCode) {
        this.zipCode = zipCode;
    }
}

